spring:
  datasource:
    url: jdbc:mysql://10.107.213.182:15010/crawler?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root


mybatis:
  #设置mybatis的mapper和model扫描路径
  mapper-locations: classpath*:/mapper/*Mapper.xml
  configuration:
    cache-enabled: false
    default-statement-timeout: 5
    map-underscore-to-camel-case: true
    use-generated-keys: true
